### ISSUE TITLE
Jekyll Error

### ISSUE THREAD

**Issue by JayofoS** [TrinityEdu/DigiNinja#5]
[Jekyll Error.docx](https://github.com/TrinityEdu/DigiNinja/files/1224360/Jekyll.Error.docx)
Good Day,
find a document attached with the error that I got from the deploy a website module. This was the fourth time I redid the section I double checked all the commands entered, I still seem to be getting it wrong. please help.

**Comment by trinity-edu-student-demo** [comment]
@JayofoS ahh I see your mistake. `cd` is a terminal command like `jekyll`. It is not a special jekyll syntax command. See the 3 command below in order which you need to run. You are missing the second step.

```
$ jekyll new personal-website
$ cd personal-website
$ jekyll server
```

Also another thing, you can attach images directly to GitHub issues comment instead of posting it on a docx.

Please let me know when it is resolved.

**Comment by vishal-reddy** [comment]
@JayofoS ahh I see your mistake. cd is a terminal command like jekyll. It is not a special jekyll syntax command. See the 3 command below in order which you need to run. You are missing the second step.

```
$ jekyll new personal-website
$ cd personal-website
$ jekyll server
```

Also another thing, you can attach images directly to GitHub issues comment instead of posting it on a docx.


Please let me know when it is resolved.

**Comment by JayofoS** [comment]
Hello  @vishal-reddy,
Jekyll issue resolved. i was able to successfully deploy the website on Github.  
Thank you very much.

**Comment by vishal-reddy** [comment]
awesome good to hear.
